#!/usr/bin/env bash

main() {
    sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &

    dunst -config "$HOME/.config/bspwm/dunst/dunstrc" &

    picom --config "$HOME/.config/bspwm/picom/picom.conf" --daemon --experimental-backends

    blueman-applet &

    nextcloud --background &

    #/usr/libexec/polkit-gnome-authentication-agent-1 &

    xsetroot -cursor_name left_ptr &

    xwallpaper --daemon --zoom "$HOME/Bilder/Wallpapers/ladybug.jpg" &>/dev/null

    export DEBUG=no
    setsid "$HOME/.config/bspwm/lemonbar/start.sh" -l &
    sleep 0.2
    "$HOME/.config/bspwm/trayer/start_trayer.sh" &

    xset s 300 5 &
    XSECURELOCK_DIM_TIME_MS=5000 xss-lock -n /usr/libexec/xsecurelock/dimmer -l -- xsecurelock &
    xautolock -time 15 -locker "systemctl suspend-then-hibernate" -detectsleep &
}

main

# vim: syntax=bash
