#!/usr/bin/env bash

main() {
    sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &

    dunst -config "$HOME/.config/bspwm/dunst/dunstrc" &

    blueman-applet &

    nextcloud --background &

    xsetroot -cursor_name left_ptr &

    xwallpaper --daemon --zoom "/home/thomas/Bilder/Wallpaper/myWallpaper/leaf-dark-blue-droplets-zaf2d5wx8xzc22ah.jpg" &>/dev/null

    export DEBUG=no
    setsid "$HOME/.config/bspwm/lemonbar/start.sh" -l &
    sleep 0.2
    "$HOME/.config/bspwm/trayer/start_trayer.sh" &

    "$HOME/.config/conky/start-conky" &

    # activate screensaver after 5 minutes
    xset s 300 10 &
    # activate DPMS
    xset +dpms
    # set DPMS Standby, Suspend, Off
    xset dpms 400 600 900

    XSECURELOCK_DIM_TIME_MS=10000 \
        xss-lock -n /usr/libexec/xsecurelock/dimmer --transfer-sleep-lock -- xsecurelock &

    xautolock -time 15 -detectsleep -locker "systemctl suspend-then-hibernate" &

    # compositor shall be invoked last to prevent glitches
    picom --config "$HOME/.config/picom/picom.conf" --daemon
}

main

# vim: syntax=bash
