#!/usr/bin/env bash

for monitor in $(bspc query -M); do
    # set the workspaces on each monitor to 1-9
    bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9
    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    #xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
done

# bspwm config
bspc config border_width            3
bspc config window_gap              5
bspc config split_ratio           0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color   "#2C3E50"
bspc config active_border_color   "#2F65FE"
bspc config focused_border_color  "#2F65FE"
bspc config presel_feedback_color "#d08770"

bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_motion_interval       5
bspc config remove_disabled_monitors      true

bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

bspc config top_padding 25

# check with 'xprop'
bspc rule -a Gimp-2.10 desktop='^6' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Evolution desktop='^5'
bspc rule -a org.gnome.Nautilus desktop='^3'
bspc rule -a KeePassXC desktop='^9' state=floating center=true follow=on
bspc rule -a Virt-manager desktop='^6' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a mpv state=floating follow=on sticky=on

# Sets master/stack layout in bspwm
bsp-layout set tall 1 -- --master-size 0.5
bsp-layout set tall 2 -- --master-size 0.5
bsp-layout set tall 3 -- --master-size 0.5
bsp-layout set tall 4 -- --master-size 0.5
bsp-layout set tall 5 -- --master-size 0.5
bsp-layout set tall 6 -- --master-size 0.5
bsp-layout set tall 7 -- --master-size 0.5
bsp-layout set tall 8 -- --master-size 0.5
bsp-layout set tall 9 -- --master-size 0.5
# Fix cursor
#xsetroot -cursor_name left_ptr

# workaround unclickable workspaces at removed second monitor
bsp config remove_disabled_monitors     true

# Startups
"$HOME/.config/bspwm/autostart"
