[module/battery]
type = internal/battery

full-at = 100
low-at = 15

poll-interval = 5

; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC

time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-foreground = ${colors.battery-charging-symbol}
format-charging-background = ${colors.module-background}
format-charging-padding = 1

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = ${colors.battery-discharging-symbol}
format-discharging-background = ${colors.module-background}
format-discharging-padding = 1

format-full = <ramp-capacity> Full
format-full-foreground = ${colors.battery-full-symbol}
format-full-background = ${colors.module-background}
format-full-padding = 1

label-charging = %percentage%%
label-discharging = %percentage%%

ramp-capacity-0 = 󱊡
ramp-capacity-1 = 󱊢
ramp-capacity-2 = 󱊣

animation-charging-0 =󱊡
animation-charging-1 =󱊢
animation-charging-2 =󱊣

animation-charging-framerate = 750

bar-capacity-width = 10
