[module/bspwm]
type = internal/bspwm

; Only show workspaces defined on the same output as the bar
; NOTE: The bspwm and XRandR monitor names must match, which they do by default.
; But if you rename your bspwm monitors with bspc -n this option will no longer
; behave correctly.
; Default: true
pin-workspaces = true

; Output mode flags after focused state label
; Default: false
inline-mode = false

; Create click handler used to focus workspace
; Default: true
enable-click = true

; Create scroll handlers used to cycle workspaces
; Default: true
enable-scroll = false

; Set the scroll cycle direction
; Default: true
reverse-scroll = false

; Use fuzzy (partial) matching on labels when assigning
; icons to workspaces
; Example: code;♚ will apply the icon to all workspaces
; containing 'code' in the label
; Default: false
fuzzy-match = false

; Only scroll through occupied workspaces
; Default: false
; New in version 3.6.0
occupied-scroll =false

; ws-icon-[0-9]+ = <label>;<icon>
; Note that the <label> needs to correspond with the bspwm workspace name
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-default = 

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(focused|urgent|occupied|empty)>
;   <label-mode> - gets replaced with <label-(monocle|tiled|fullscreen|floating|locked|sticky|private)>
; Default: <label-state>
format = <label-state> <label-mode>

; Available tokens:
;   %name%
; Default: %name%
label-monitor = %name%

; If any values for label-dimmed-N are defined, the workspace/mode
; colors will get overridden with those values if the monitor is out of focus
; To only override workspaces in a specific state, use:
;   label-dimmed-focused
;   label-dimmed-occupied
;   label-dimmed-urgent
;   label-dimmed-empty
;label-dimmed-foreground = #555
;label-dimmed-underline = ${bar/top.background}
;label-dimmed-focused-background = #f00

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-focused = %icon%
label-focused-foreground = ${colors.active-tag-symbol}
label-focused-background = ${colors.active-tag-background}
label-focused-underline= ${colors.active-tag-underline}
label-focused-padding = 1
label-focused-margin = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-occupied = %icon%
label-occupied-foreground = ${colors.occupied-tag-symbol}
label-occupied-background = ${colors.occupied-tag-background}
;label-occupied-underline= ${colors.occupied-tag-underline}
label-occupied-padding = 1
label-occupied-margin = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-urgent = %icon%
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.white}
label-urgent-underline = ${colors.red}
label-urgent-padding = 1
label-urgent-margin = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-empty = %icon%
label-empty-foreground = ${colors.empty-tag-symbol}
label-empty-background = ${colors.empty-tag-background}
label-empty-padding = 1
label-empty-margin = 1

; The following labels will be used to indicate the layout/mode
; for the focused workspace. Requires <label-mode>
;
; Available tokens:
;   None
label-monocle = " [MONOCLE] "
label-monocle-foreground = ${colors.monocle-symbol}
label-monocle-background = ${colors.module-background}
label-tiled = " [TILED] "
label-tiled-foreground = ${colors.tiled-symbol}
label-tiled-background = ${colors.module-background}
label-fullscreen = " [FULLSCREEN] "
label-fullscreen-foreground = ${colors.fullscreen-symbol}
label-fullscreen-background = ${colors.module-background}
label-floating = " [FLOATING] "
label-floating-foreground = ${colors.floating-symbol}
label-floating-background = ${colors.module-background}
label-pseudotiled = " [PSEUDOTILED] "
label-pseudotiled-foreground = ${colors.pseudotiled-symbol}
label-pseudotiled-background = ${colors.module-background}
label-locked = "  "
label-locked-foreground = ${colors.locked-symbol}
label-locked-background = ${colors.module-background}
label-sticky = "  "
label-sticky-foreground = ${colors.sticky-symbol}
label-sticky-background = ${colors.module-background}
label-private =  "  "
label-private-foreground = ${colors.private-symbol}
label-private-background = ${colors.module-background}

; Separator in between workspaces
;label-separator = │
;label-separator-padding = 0
;label-separator-foreground = ${colors.red}

;format-foreground = #fff111
format-background = ${colors.black}

