[module/date]
type = internal/date
interval = 10
date = %d.%m.%Y
time = %H:%M
; %{A1:command: A2:command: A3:command: A4:command: A5:command:}
format = %{A1:notify-send "test":}<label>%{A}
format-background = ${colors.module-background}
format-foreground = ${colors.date-symbol}
format-padding = 1
#format-marging = 1
label = %date%  %time%
click-right = notify-send "rechts"
