[module/launcher]
type = custom/text

click-left = rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/bspwm/rofi/launcher.rasi
;content = 
content = 
content-background = ${colors.module-background}
content-foreground = ${colors.launcher-symbol}
content-padding = 1
