[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected =

format-connected-padding = 0
format-disconnected-padding = 0
#format-connected-margin = 1

format-foreground = ${colors.lightblue}
format-background = ${colors.module-background}

click-right = alacritty -e sh -c 'nmtui'

[module/eth]
inherit = network-base
interface-type = wired
label-connected = 

[module/wlan]
inherit = network-base
interface = ${env:WIRELESS}

click-left = notify-send "nix"

interface-type = wireless
format-connected = <ramp-signal> <label-connected>
label-connected = %signal%%
label-connected-background = ${colors.module-background}
label-disconnected = 󰤭
;label-disconnected-background = ${colors.module-background}
label-connected-foreground = ${colors.lightblue}

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

ramp-signal-foreground = ${colors.lightblue}
