[colors]
red         = #FF0000
white       = #ffffff
background  = #002b36
foreground  = #839496
color0      = #073642
color1      = #dc322f
color2      = #859900
color3      = #b58900
color4      = #268bd2
color5      = #d33682
color6      = #2aa198
color7      = #eee8d5
color8      = #002b36
color9      = #cb4b16
color10     = #586e75
color11     = #657b83
color12     = #839496
color13     = #6c71c4
color14     = #93a1a1
color15     = #fdf6e3

grey        = #93a1a1
lightgrey   = #eee8d5
yellow      = #b58900
orange      = #e0af68
black       = #000000
lightyellow = #FFFF33
green       = #01D127
darkgrey    = #272e33
lightred    = #e67e80
lightgreen  = #83c092
lightblue   = #268bd2

; color of bar excluding tags and modules
bar-background = ${self.black}
; color of tag-underlines, not focused but occupied
occupied-tag-underline = ${self.orange}
; color of active tag-field except its underline and symbol
active-tag-background = ${self.black}
; color of tag-underline of active tag
active-tag-underline = ${self.green}
; color of symbol/text of active tag
active-tag-symbol = ${self.green}
; color of symbol/text of occupied tag
occupied-tag-symbol = ${self.color1}
; color of tag-field except its underline and symbol
occupied-tag-background = ${self.black}
; color of symbol of empty (not active, not occupied) tag
empty-tag-symbol = ${self.grey}
; color of tag-field of non occupied or active tag
empty-tag-background = ${self.black}
; color of monocle symbol/text
monocle-symbol = ${self.grey}

tiled-symbol = ${self.grey}

fullscreen-symbol = ${self.grey}

floating-symbol = ${self.grey}

pseudotiled-symbol = ${self.grey}

locked-symbol = ${self.grey}

sticky-symbol = ${self.grey}

private-symbol = ${self.grey}
; color of background of modules (right side of bar)
module-background = ${self.darkgrey}
; following colors of modul symbols
volume-symbol = ${self.orange}

battery-discharging-symbol = ${self.lightred}
battery-charging-symbol = ${self.lightred}
battery-full-symbol = ${self.lightred}

date-symbol = ${self.green}

title-symbol = ${self.grey}

launcher-symbol = ${self.red}
